### PR TITLE
metafieldParser()

### LINKED ISSUE #39: [BUG] `parseMetafield` doesn't work with single line text list metafields
**Describe the bug**

The `parseMetafield` and `parseMetafieldValue` utilities don't return an array of strings for metafields of type `list.single_line_text_field`.

**To Reproduce**

1. Add metafield definition
2. Expose metafield to Storefront API
3. Select "Single line text" and "List of values"
4. Query product with metafield
5. Parse metafield using `parseMetafield` or`parseMetafieldValue`

**Expected behaviour**

The `parseMetafield` and `parseMetafieldValue` utilities should return an array of strings instead of a stringified array for this type of metafield.

**Additional context**

- Hydrogen version `1.3.2`
- Node version `16.14.0`
- Device details `iMac (macOS Monterey 12.4)`

### PR DESCRIPTION
**Pull request by frehner**
Introduce a better metafield parser, and handle all the new types of metafields that were added in 2022-10. 

Closes #39

### CODE REVIEW

**Comment by frehner** [comment]
Ready for review!

File: packages/react/src/Metafield.tsx [hunk 1]
```diff
@@ -190,6 +190,7 @@ export function Metafield<ComponentGeneric extends ElementType>(
  * The `parseMetafield` utility transforms a [Metafield](https://shopify.dev/api/storefront/reference/common-objects/Metafield)
  * into a new object whose `values` have been parsed according to the metafield `type`.
  * If the metafield is `null`, then it returns `null` back.
+ * @deprecated `parseMetafield()` is unsupported and will be removed in a future version. Use `metafieldParser()` instead
  */
 export function parseMetafield(
```
Comment (lordofthecactus) [inline packages/react/src/Metafield.tsx:195]: should the warn be added when people use this?

File: packages/react/src/Metafield.tsx [hunk 2]
```diff
@@ -220,6 +221,7 @@ export function parseMetafield(
 
 /**
  * The `parseMetafieldValue` function parses a [Metafield](https://shopify.dev/api/storefront/reference/common-objects/metafield)'s `value` from a string into a sensible type corresponding to the [Metafield](https://shopify.dev/api/storefront/reference/common-objects/metafield)'s `type`.
+ * @deprecated `parseMetafieldValue()` is unsupported and will be removed in a future version. Use `metafieldParser()` instead
```
Comment (lordofthecactus) [inline packages/react/src/Metafield.tsx:224]: same as above

File: packages/react/src/metafield-parser.test.ts [hunk 3]
```diff
@@ -0,0 +1,539 @@
...
+
+      // without an extra generic, we just mark it as "unknown"
+      const parsed = metafieldParser<ParsedMetafields['json']>(myJson);
+      // note that with "unknown", you have to cast it as something
+      expect((parsed?.parsedValue as {test: string})?.test === 'testing').toBe(
+        true
+      );
+      expectType<null | unknown>(parsed?.parsedValue);
+
+      // with an extra generic, we use can use that as the type instead
```
Comment (lordofthecactus) [inline packages/react/src/metafield-parser.test.ts:123]:
```suggestion
      // with an extra generic, we can use that as the type instead
```

File: packages/react/src/metafield-parser.test.ts [hunk 4]
```diff
@@ -0,0 +1,539 @@
...
+      const parsedOtherType =
+        metafieldParser<ParsedMetafields<MyJson>['json']>(myJson);
+      expect(parsedOtherType.type === 'json').toBe(true);
+      expect(parsedOtherType.parsedValue?.test === 'testing').toBe(true);
+      expect(parsedOtherType.parsedValue?.bool === false).toBe(true);
+      expect(parsedOtherType.parsedValue?.deep?.numb === 7).toBe(true);
+      expectType<null | MyJson>(parsedOtherType.parsedValue);
```
Comment (lordofthecactus) [inline packages/react/src/metafield-parser.test.ts:130]: cool! 💯

File: packages/react/src/metafield-parser.test.ts [hunk 5]
```diff
@@ -0,0 +1,539 @@
...
+    });
+
+    it(`money`, () => {
+      const parsed = metafieldParser<ParsedMetafields['money']>({
+        type: 'money',
+        value: JSON.stringify({amount: '12', currencyCode: 'USD'}),
+      });
+      // TODO: amount should be a number, not a string
```
Comment (lordofthecactus) [inline packages/react/src/metafield-parser.test.ts:138]: 🤔  I'm wondering about this. If I remember correctly, strings are a way to avoid numerical precision errors.

**Review by lordofthecactus — APPROVED** [review]
✅  Nice! man! left a couple of comments

File: packages/react/src/Metafield.tsx (hunk 1 above)
Comment (frehner) [reply packages/react/src/Metafield.tsx:195]: Ah good point, will add!
